version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    expose:
      - "8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - MODE=dev

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fastapi
