from datetime import datetime
from typing import List
from fastapi import APIRouter, Query

from app.api.routes.salary_management.dto.entire_salary_info_response_dto import EntireSalaryInfoResponseDTO, UnusedAnnualLeaveAllowanceDTO, UsedAnnualLeaveDeductionDTO


router = APIRouter()


@router.get("/{branch_id}/salary-management")
async def get_salary_management(branch_id: int, part_id: int = Query(None), year: int = Query(datetime.now().year), month: int = Query(datetime.now().month)) -> List[EntireSalaryInfoResponseDTO]:
    mock_data = {
        1: [  # branch_id 1 - 1번 지점
            EntireSalaryInfoResponseDTO(
                id=1,
                user_id=101,
                name="김철수",
                part_id=1,  # 1번 지점 의사
                part_name="의사", 
                hire_date=datetime(2020, 1, 15).date(),
                    resignation_date=None,
                monthly_salary=3500000,
                base_salary=2800000,
                meal_allowance=100000,
                fixed_overtime_allowance=200000,
                annual_leave_allowance=150000,
                holiday_allowance=100000,
                    night_work_allowance=80000,
                    duty_allowance=200000,
                    insentive_allowance=300000,
                    holiday_work_allowance=120000,
                    previous_month_unpaid=0,
                    overtime_allowance=150000,
                    weekend_work_allowance=100000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=5,
                        daily_salary=100000,
                        total_amount=500000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=2,
                        total_amount=200000
                    ),
                    attendance_deduction=0,
                    vehicle_maintenance_allowance=200000,
                    total_salary=4550000,
                    hourly_wage=16827
                ),
                EntireSalaryInfoResponseDTO(
                    id=2,
                    user_id=102,
                    name="이영희",
                    part_id=2,  # 1번 지점 간호사
                    part_name="간호사",
                    hire_date=datetime(2019, 3, 1).date(),
                    resignation_date=None,
                    monthly_salary=4000000,
                    base_salary=3200000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=250000,
                    annual_leave_allowance=180000,
                    holiday_allowance=120000,
                    night_work_allowance=90000,
                    duty_allowance=250000,
                    insentive_allowance=400000,
                    holiday_work_allowance=140000,
                    previous_month_unpaid=0,
                    overtime_allowance=200000,
                    weekend_work_allowance=150000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=3,
                        daily_salary=120000,
                        total_amount=360000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=1,
                        total_amount=120000
                    ),
                    attendance_deduction=50000,
                    vehicle_maintenance_allowance=200000,
                    total_salary=4940000,
                    hourly_wage=19231
                ),
                EntireSalaryInfoResponseDTO(
                    id=3,
                    user_id=103,
                    name="박지성",
                    part_id=3,  # 1번 지점 간호조무사
                    part_name="간호조무사",
                    hire_date=datetime(2021, 6, 1).date(),
                    resignation_date=None,
                    monthly_salary=3800000,
                    base_salary=3000000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=220000,
                    annual_leave_allowance=160000,
                    holiday_allowance=110000,
                    night_work_allowance=85000,
                    duty_allowance=220000,
                    insentive_allowance=500000,
                    holiday_work_allowance=130000,
                    previous_month_unpaid=100000,
                    overtime_allowance=180000,
                    weekend_work_allowance=130000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=7,
                        daily_salary=110000,
                        total_amount=770000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=3,
                        total_amount=330000
                    ),
                    attendance_deduction=0,
                    vehicle_maintenance_allowance=200000,
                    total_salary=4580000,
                    hourly_wage=8000
                ),
                EntireSalaryInfoResponseDTO(
                    id=4,
                    user_id=104,
                    name="손흥민",
                    part_id=4,  # 1번 지점 코디네이터
                    part_name="코디네이터",
                    hire_date=datetime(2022, 1, 10).date(),
                    resignation_date=None,
                    monthly_salary=3300000,
                    base_salary=2600000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=180000,
                    annual_leave_allowance=140000,
                    holiday_allowance=90000,
                    night_work_allowance=70000,
                    duty_allowance=180000,
                    insentive_allowance=250000,
                    holiday_work_allowance=110000,
                    previous_month_unpaid=0,
                    overtime_allowance=130000,
                    weekend_work_allowance=80000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=4,
                        daily_salary=90000,
                        total_amount=360000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=2,
                        total_amount=180000
                    ),
                    attendance_deduction=30000,
                    vehicle_maintenance_allowance=200000,
                    total_salary=3690000,
                    hourly_wage=15865
                ),
                EntireSalaryInfoResponseDTO(
                    id=5,
                    user_id=105,
                    name="김민재",
                    part_id=1,  # 1번 지점 의사
                    part_name="의사",
                    hire_date=datetime(2020, 8, 15).date(),
                    resignation_date=None,
                    monthly_salary=3600000,
                    base_salary=2900000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=210000,
                    annual_leave_allowance=155000,
                    holiday_allowance=105000,
                    night_work_allowance=75000,
                    duty_allowance=210000,
                    insentive_allowance=320000,
                    holiday_work_allowance=125000,
                    previous_month_unpaid=0,
                    overtime_allowance=160000,
                    weekend_work_allowance=110000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=6,
                        daily_salary=105000,
                        total_amount=630000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=1,
                        total_amount=105000
                    ),
                    attendance_deduction=0,
                    vehicle_maintenance_allowance=200000,
                    total_salary=4825000,
                    hourly_wage=17308
                )
            ],
            2: [  # branch_id 2 - 2번 지점
                EntireSalaryInfoResponseDTO(
                    id=6,
                    user_id=201,
                    name="이강인",
                    part_id=5,  # 2번 지점 의사
                    part_name="의사",
                    hire_date=datetime(2020, 3, 1).date(),
                    resignation_date=None,
                    monthly_salary=3700000,
                    base_salary=2950000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=215000,
                    annual_leave_allowance=158000,
                    holiday_allowance=108000,
                    night_work_allowance=78000,
                    duty_allowance=215000,
                    insentive_allowance=330000,
                    holiday_work_allowance=128000,
                    previous_month_unpaid=0,
                    overtime_allowance=165000,
                    weekend_work_allowance=115000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=4,
                        daily_salary=108000,
                        total_amount=432000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=2,
                        total_amount=216000
                    ),
                    attendance_deduction=0,
                    vehicle_maintenance_allowance=200000,
                    total_salary=4700000,
                    hourly_wage=17788
                ),
                EntireSalaryInfoResponseDTO(
                    id=7,
                    user_id=202,
                    name="황인범",
                    part_id=6,  # 2번 지점 간호사
                    part_name="간호사",
                    hire_date=datetime(2021, 5, 1).date(),
                    resignation_date=None,
                    monthly_salary=3200000,
                    base_salary=2500000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=180000,
                    annual_leave_allowance=140000,
                    holiday_allowance=95000,
                    night_work_allowance=70000,
                    duty_allowance=190000,
                    insentive_allowance=280000,
                    holiday_work_allowance=115000,
                    previous_month_unpaid=0,
                    overtime_allowance=145000,
                    weekend_work_allowance=95000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=3,
                        daily_salary=95000,
                        total_amount=285000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=1,
                        total_amount=95000
                    ),
                    attendance_deduction=20000,
                    vehicle_maintenance_allowance=200000,
                    total_salary=3800000,
                    hourly_wage=15385
                ),
                EntireSalaryInfoResponseDTO(
                    id=8,
                    user_id=203,
                    name="조규성",
                    part_id=7,  # 2번 지점 간호조무사
                    part_name="간호조무사",
                    hire_date=datetime(2022, 2, 15).date(),
                    resignation_date=None,
                    monthly_salary=2800000,
                    base_salary=2200000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=160000,
                    annual_leave_allowance=120000,
                    holiday_allowance=85000,
                    night_work_allowance=65000,
                    duty_allowance=170000,
                    insentive_allowance=250000,
                    holiday_work_allowance=100000,
                    previous_month_unpaid=0,
                    overtime_allowance=130000,
                    weekend_work_allowance=85000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=2,
                        daily_salary=85000,
                        total_amount=170000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=1,
                        total_amount=85000
                    ),
                    attendance_deduction=0,
                    vehicle_maintenance_allowance=200000,
                    total_salary=3450000,
                    hourly_wage=13462
                ),
                EntireSalaryInfoResponseDTO(
                    id=9,
                    user_id=204,
                    name="김영권",
                    part_id=8,  # 2번 지점 코디네이터
                    part_name="코디네이터",
                    hire_date=datetime(2021, 8, 1).date(),
                    resignation_date=None,
                    monthly_salary=2900000,
                    base_salary=2300000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=165000,
                    annual_leave_allowance=125000,
                    holiday_allowance=88000,
                    night_work_allowance=68000,
                    duty_allowance=175000,
                    insentive_allowance=260000,
                    holiday_work_allowance=105000,
                    previous_month_unpaid=0,
                    overtime_allowance=135000,
                    weekend_work_allowance=88000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=4,
                        daily_salary=88000,
                        total_amount=352000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=2,
                        total_amount=176000
                    ),
                    attendance_deduction=15000,
                    vehicle_maintenance_allowance=200000,
                    total_salary=3570000,
                    hourly_wage=13942
                ),
                EntireSalaryInfoResponseDTO(
                    id=10,
                    user_id=205,
                    name="김진수",
                    part_id=6,  # 2번 지점 간호사
                    part_name="간호사",
                    hire_date=datetime(2020, 11, 1).date(),
                    resignation_date=None,
                    monthly_salary=3100000,
                    base_salary=2400000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=170000,
                    annual_leave_allowance=130000,
                    holiday_allowance=90000,
                    night_work_allowance=70000,
                    duty_allowance=180000,
                    insentive_allowance=270000,
                    holiday_work_allowance=110000,
                    previous_month_unpaid=0,
                    overtime_allowance=140000,
                    weekend_work_allowance=90000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=5,
                        daily_salary=90000,
                        total_amount=450000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=1,
                        total_amount=90000
                    ),
                    attendance_deduction=10000,
                    vehicle_maintenance_allowance=200000,
                    total_salary=3720000,
                    hourly_wage=14904
                )
            ],
            3: [  # branch_id 3 - 3번 지점
                EntireSalaryInfoResponseDTO(
                    id=11,
                    user_id=301,
                    name="황희찬",
                    part_id=9,  # 3번 지점 의사
                    part_name="의사",
                    hire_date=datetime(2021, 4, 1).date(),
                    resignation_date=None,
                    monthly_salary=3900000,
                    base_salary=3100000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=225000,
                    annual_leave_allowance=165000,
                    holiday_allowance=115000,
                    night_work_allowance=82000,
                    duty_allowance=225000,
                    insentive_allowance=350000,
                    holiday_work_allowance=135000,
                    previous_month_unpaid=0,
                    overtime_allowance=175000,
                    weekend_work_allowance=125000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=5,
                        daily_salary=115000,
                        total_amount=575000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=2,
                        total_amount=230000
                    ),
                    attendance_deduction=0,
                    vehicle_maintenance_allowance=200000,
                    total_salary=4900000,
                    hourly_wage=18750
                ),
                EntireSalaryInfoResponseDTO(
                    id=12,
                    user_id=302,
                    name="정우영",
                    part_id=10,  # 3번 지점 간호사
                    part_name="간호사",
                    hire_date=datetime(2020, 9, 15).date(),
                    resignation_date=None,
                    monthly_salary=3300000,
                    base_salary=2600000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=185000,
                    annual_leave_allowance=145000,
                    holiday_allowance=98000,
                    night_work_allowance=72000,
                    duty_allowance=195000,
                    insentive_allowance=290000,
                    holiday_work_allowance=118000,
                    previous_month_unpaid=0,
                    overtime_allowance=150000,
                    weekend_work_allowance=98000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=6,
                        daily_salary=98000,
                        total_amount=588000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=1,
                        total_amount=98000
                    ),
                    attendance_deduction=25000,
                    vehicle_maintenance_allowance=200000,
                    total_salary=3916000,
                    hourly_wage=15865
                ),
                EntireSalaryInfoResponseDTO(
                    id=13,
                    user_id=303,
                    name="오현규",
                    part_id=11,  # 3번 지점 코디네이터
                    part_name="코디네이터",
                    hire_date=datetime(2022, 3, 1).date(),
                    resignation_date=None,
                    monthly_salary=2700000,
                    base_salary=2100000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=155000,
                    annual_leave_allowance=115000,
                    holiday_allowance=82000,
                    night_work_allowance=62000,
                    duty_allowance=165000,
                    insentive_allowance=240000,
                    holiday_work_allowance=95000,
                    previous_month_unpaid=0,
                    overtime_allowance=125000,
                    weekend_work_allowance=82000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=3,
                        daily_salary=82000,
                        total_amount=246000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=1,
                        total_amount=82000
                    ),
                    attendance_deduction=0,
                    vehicle_maintenance_allowance=200000,
                    total_salary=3285000,
                    hourly_wage=13942
                ),
                EntireSalaryInfoResponseDTO(
                    id=14,
                    user_id=304,
                    name="조현우",
                    part_id=12,  # 3번 지점 간호조무사
                    part_name="간호조무사",
                    hire_date=datetime(2021, 7, 1).date(),
                    resignation_date=None,
                    monthly_salary=2600000,
                    base_salary=2000000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=150000,
                    annual_leave_allowance=110000,
                    holiday_allowance=80000,
                    night_work_allowance=60000,
                    duty_allowance=160000,
                    insentive_allowance=230000,
                    holiday_work_allowance=90000,
                    previous_month_unpaid=0,
                    overtime_allowance=120000,
                    weekend_work_allowance=80000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=4,
                        daily_salary=80000,
                        total_amount=320000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=2,
                        total_amount=160000
                    ),
                    attendance_deduction=0,
                    vehicle_maintenance_allowance=200000,
                    total_salary=3140000,
                    hourly_wage=12500
                ),
                EntireSalaryInfoResponseDTO(
                    id=15,
                    user_id=305,
                    name="김승규",
                    part_id=10,  # 3번 지점 간호사
                    part_name="간호사",
                    hire_date=datetime(2020, 12, 1).date(),
                    resignation_date=None,
                    monthly_salary=3000000,
                    base_salary=2300000,
                    meal_allowance=100000,
                    fixed_overtime_allowance=165000,
                    annual_leave_allowance=125000,
                    holiday_allowance=85000,
                    night_work_allowance=65000,
                    duty_allowance=175000,
                    insentive_allowance=260000,
                    holiday_work_allowance=105000,
                    previous_month_unpaid=0,
                    overtime_allowance=135000,
                    weekend_work_allowance=85000,
                    unused_annual_leave_allowance=UnusedAnnualLeaveAllowanceDTO(
                        count=5,
                        daily_salary=85000,
                        total_amount=425000
                    ),
                    used_annual_leave_deduction=UsedAnnualLeaveDeductionDTO(
                        count=1,
                        total_amount=85000
                    ),
                    attendance_deduction=0,
                    vehicle_maintenance_allowance=200000,
                    total_salary=3625000,
                    hourly_wage=14423
                )
            ]
        }.get(branch_id, [])
    if not part_id:
        return mock_data
    return [salary for salary in mock_data if salary.part_id == part_id]