"""delete_board+post+comment

Revision ID: 0ada626cb05a
Revises: ec4aacfbda6b
Create Date: 2024-10-16 13:47:34.450472

"""
from typing import Sequence, Union
from sqlalchemy.exc import OperationalError, ProgrammingError
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ada626cb05a'
down_revision: Union[str, None] = 'ec4aacfbda6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.drop_constraint('comments_ibfk_1', 'comments', type_='foreignkey')
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.drop_constraint('comments_ibfk_3', 'comments', type_='foreignkey')
    op.drop_constraint('posts_ibfk_2', 'posts', type_='foreignkey')
    op.drop_constraint('posts_ibfk_3', 'posts', type_='foreignkey')
    op.drop_constraint('boards_ibfk_1', 'boards', type_='foreignkey')
    op.drop_constraint('branch_policies_ibfk_1', 'branch_policies', type_='foreignkey')
    op.drop_table('posts')
    op.drop_index('category_name', table_name='boards')
    op.drop_table('comments')
    op.drop_table('boards')
    op.drop_index('branch_code', table_name='branch_policies')
    op.drop_table('branch_policies')
    ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_yn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='comments_ibfk_1'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='comments_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('branch_policies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('representative_doctor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('branch_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('business_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('seal_image_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('nameplate_image_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_yn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='branch_policies_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('branch_code', 'branch_policies', ['branch_code'], unique=True)
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('content', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_yn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='posts_ibfk_1'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='posts_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('boards',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('read_authority', mysql.ENUM('MSO 최고권한', '최고관리자', '관리자', '사원', '퇴사자'), nullable=False),
    sa.Column('write_authority', mysql.ENUM('MSO 최고권한', '최고관리자', '관리자', '사원', '퇴사자'), nullable=False),
    sa.Column('notice_authority', mysql.ENUM('MSO 최고권한', '최고관리자', '관리자', '사원', '퇴사자'), nullable=False),
    sa.Column('part_division', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('allow_comment', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_yn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='boards_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('category_name', 'boards', ['category_name'], unique=True)
    # ### end Alembic commands ###
