"""v10

Revision ID: 0dd8a6013dac
Revises: 480b8807d632
Create Date: 2024-11-01 11:27:45.502203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0dd8a6013dac'
down_revision: Union[str, None] = '480b8807d632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. connection_logs 관련 작업
    # op.drop_index('ix_connection_logs_id', table_name='connection_logs')
    # op.drop_table('connection_logs')
    
    # 2. leave_histories 관련 작업
    # 먼저 컬럼 추가
    # op.add_column('leave_histories', sa.Column('part_id', sa.Integer(), nullable=True))
    # 그 다음 제약조건 추가
    # op.create_unique_constraint('uq_user_application_date', 'leave_histories', ['user_id', 'application_date'])
    # op.create_foreign_key(None, 'leave_histories', 'parts', ['part_id'], ['id'])
    
    # 3. user_leaves_days 관련 작업
    # op.add_column('user_leaves_days', sa.Column('part_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_leaves_days_ibfk_1', 'user_leaves_days', type_='foreignkey')
    op.drop_constraint('user_leaves_days_ibfk_2', 'user_leaves_days', type_='foreignkey')  # branch_id FK
    op.drop_constraint('user_leaves_days_ibfk_4', 'user_leaves_days', type_='foreignkey')
    op.alter_column('user_leaves_days', 'branch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'user_leaves_days', 'branches', ['branch_id'], ['id'])  # branch FK 재추가
    op.create_foreign_key(None, 'user_leaves_days', 'parts', ['part_id'], ['id'])
    op.drop_column('user_leaves_days', 'leave_history_id')
    op.drop_column('user_leaves_days', 'approver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_leaves_days', sa.Column('approver_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_leaves_days', sa.Column('leave_history_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_leaves_days', type_='foreignkey')
    op.create_foreign_key('user_leaves_days_ibfk_4', 'user_leaves_days', 'leave_histories', ['leave_history_id'], ['id'])
    op.create_foreign_key('user_leaves_days_ibfk_1', 'user_leaves_days', 'users', ['approver_id'], ['id'])
    op.alter_column('user_leaves_days', 'branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('user_leaves_days', 'part_id')
    op.drop_constraint(None, 'leave_histories', type_='foreignkey')
    op.drop_constraint('uq_user_application_date', 'leave_histories', type_='unique')
    op.create_table('connection_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('connection_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_connection_logs_id', 'connection_logs', ['id'], unique=False)
    # ### end Alembic commands ###
