"""v16

Revision ID: 1bb64a706470
Revises: 803f44e21b40
Create Date: 2024-11-04 12:19:06.853159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1bb64a706470'
down_revision: Union[str, None] = '803f44e21b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('contract_type', sa.Enum('WORK', 'SALARY', 'PART_TIME', name='contracttype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_type', sa.Enum('ELEMENTARY', 'MIDDLE', 'HIGH', 'UNIVERSITY', 'GRADUATE', name='schooltype'), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('graduation_type', sa.Enum('GRADUATED', 'EXPECTED', 'IN_PROGRESS', 'LEAVE', 'DROPOUT', name='graduationtype'), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_offs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_off_type', sa.Enum('PARENTAL', 'INDUSTRIAL_ACCIDENT', name='timeofftype'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('leave_histories', 'total_leave_days')
    op.drop_column('leave_histories', 'regular_days')
    op.drop_column('leave_histories', 'increased_days')
    op.drop_column('leave_histories', 'is_paid')
    op.add_column('part_timer_work_contracts', sa.Column('contract_info_id', sa.Integer(), nullable=False))
    op.add_column('part_timer_work_contracts', sa.Column('daily_break_time', sa.Integer(), nullable=False))
    op.add_column('part_timer_work_contracts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('part_timer_work_contracts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('part_timer_work_contracts', sa.Column('deleted_yn', sa.String(length=1), nullable=True))
    op.drop_constraint('part_timer_work_contracts_ibfk_1', 'part_timer_work_contracts', type_='foreignkey')
    op.create_foreign_key(None, 'part_timer_work_contracts', 'contract_info', ['contract_info_id'], ['id'])
    op.drop_column('part_timer_work_contracts', 'user_id')
    op.drop_column('user_leaves_days', 'regular_leave_days')
    op.drop_column('user_leaves_days', 'paid_leave_days')
    op.add_column('users', sa.Column('stay_end_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('detail_address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('resident_registration_number', sa.String(length=20), nullable=True))
    op.alter_column('users', 'position',
               existing_type=mysql.ENUM('MSO 최고권한', '최고관리자', '통합관리자', '관리자', '사원', '퇴사자', '휴직자', '임시생성'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('users', 'last_career_start_date')
    op.drop_column('users', 'sabbatical_start_date')
    op.drop_column('users', 'last_company')
    op.drop_column('users', 'last_position')
    op.drop_column('users', 'education')
    op.drop_column('users', 'last_career_end_date')
    op.drop_column('users', 'sabbatical_end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sabbatical_end_date', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('last_career_end_date', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('education', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('last_position', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('last_company', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('sabbatical_start_date', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('last_career_start_date', sa.DATE(), nullable=True))
    op.alter_column('users', 'position',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('MSO 최고권한', '최고관리자', '통합관리자', '관리자', '사원', '퇴사자', '휴직자', '임시생성'),
               existing_nullable=False)
    op.drop_column('users', 'resident_registration_number')
    op.drop_column('users', 'detail_address')
    op.drop_column('users', 'stay_end_date')
    op.add_column('user_leaves_days', sa.Column('paid_leave_days', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False))
    op.add_column('user_leaves_days', sa.Column('regular_leave_days', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False))
    op.add_column('part_timer_work_contracts', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'part_timer_work_contracts', type_='foreignkey')
    op.create_foreign_key('part_timer_work_contracts_ibfk_1', 'part_timer_work_contracts', 'users', ['user_id'], ['id'])
    op.drop_column('part_timer_work_contracts', 'deleted_yn')
    op.drop_column('part_timer_work_contracts', 'updated_at')
    op.drop_column('part_timer_work_contracts', 'created_at')
    op.drop_column('part_timer_work_contracts', 'daily_break_time')
    op.drop_column('part_timer_work_contracts', 'contract_info_id')
    op.add_column('leave_histories', sa.Column('is_paid', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True))
    op.add_column('leave_histories', sa.Column('increased_days', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True))
    op.add_column('leave_histories', sa.Column('regular_days', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True))
    op.add_column('leave_histories', sa.Column('total_leave_days', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True))
    op.drop_table('time_offs')
    op.drop_table('educations')
    op.drop_table('careers')
    # ### end Alembic commands ###
