"""v19

Revision ID: 25fc952e4b37
Revises: 5e727b4e9d6e
Create Date: 2024-11-04 21:26:56.705583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25fc952e4b37'
down_revision: Union[str, None] = '5e727b4e9d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_menus', 'part_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_menus', 'part_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
