"""create annual leave approval, grant

Revision ID: 2601c093c87e
Revises: e3440c11d246
Create Date: 2024-10-21 14:51:34.161335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2601c093c87e'
down_revision: Union[str, None] = 'e3440c11d246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_annual_leave_approval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('top_auto_approval', sa.Boolean(), nullable=True),
    sa.Column('total_auto_approval', sa.Boolean(), nullable=True),
    sa.Column('part_auto_approval', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_annual_leave_grant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('account_based_january_1st', sa.Enum('초기화', '다음해로 이월', name='account_january_1st'), nullable=False, comment='매 년 1월 1일기준'),
    sa.Column('account_based_less_than_year', sa.Enum('당해년도 일괄 부여', '매 월 1개씩 부여', name='account_less_than_year'), nullable=False, comment='근속년수 1년 미만'),
    sa.Column('account_based_decimal_point', sa.Enum('0.5 기준 올림', '절삭', '올림', '반올림', name='account_decimal_point'), nullable=False, comment='소수점처리'),
    sa.Column('entry_date_based_remaining_leave', sa.Enum('초기화', '다음해로 이월', name='entry_date_based'), nullable=False, comment='매 년 입사일 기준'),
    sa.Column('condition_based_month', sa.Integer(), nullable=False),
    sa.Column('condition_based_cnt', sa.Integer(), nullable=False),
    sa.Column('condition_based_type', sa.Enum('월', '일', name='condition_based_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auto_overtime_policies', sa.Column('top_auto_applied', sa.Boolean(), nullable=True))
    op.add_column('auto_overtime_policies', sa.Column('total_auto_applied', sa.Boolean(), nullable=True))
    op.add_column('auto_overtime_policies', sa.Column('part_auto_applied', sa.Boolean(), nullable=True))
    op.drop_column('auto_overtime_policies', 'manager_auto_applied')
    op.drop_column('auto_overtime_policies', 'top_manager_auto_applied')
    op.drop_column('auto_overtime_policies', 'employee_auto_applied')
    op.drop_column('closed_days', 'is_sunday')
    op.drop_column('leave_categories', 'is_leave_of_absence')
    op.add_column('parts', sa.Column('auto_annual_leave_grant', sa.Enum('수동부여', '회계기준 부여', '입사일 기준 부여', '조건별 부여', name='part_auto_annual_leave_grant'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'auto_annual_leave_grant')
    op.add_column('leave_categories', sa.Column('is_leave_of_absence', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('closed_days', sa.Column('is_sunday', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('auto_overtime_policies', sa.Column('employee_auto_applied', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('auto_overtime_policies', sa.Column('top_manager_auto_applied', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('auto_overtime_policies', sa.Column('manager_auto_applied', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('auto_overtime_policies', 'part_auto_applied')
    op.drop_column('auto_overtime_policies', 'total_auto_applied')
    op.drop_column('auto_overtime_policies', 'top_auto_applied')
    op.drop_table('auto_annual_leave_grant')
    op.drop_table('auto_annual_leave_approval')
    # ### end Alembic commands ###
