"""loadl_rds_v2

Revision ID: 2d6aa8b25a6e
Revises: 860279e01446
Create Date: 2024-10-28 17:09:44.202393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d6aa8b25a6e'
down_revision: Union[str, None] = '860279e01446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_based_annual_leave_grant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('account_based_january_1st', sa.Enum('초기화', '다음해로 이월'), nullable=False, comment='매 년 1월 1일기준'),
    sa.Column('account_based_less_than_year', sa.Enum('당해년도 일괄 부여', '매 월 1개씩 부여'), nullable=False, comment='근속년수 1년 미만'),
    sa.Column('account_based_decimal_point', sa.Enum('0.5 기준 올림', '절삭', '올림', '반올림'), nullable=False, comment='소수점처리'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condition_based_annual_leave_grant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('condition_based_month', sa.Integer(), nullable=False),
    sa.Column('condition_based_cnt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_date_based_annual_leave_grant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('entry_date_based_remaining_leave', sa.Enum('초기화', '다음해로 이월'), nullable=False, comment='매 년 입사일 기준'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('auto_annual_leave_grant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_annual_leave_grant',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_based_january_1st', mysql.ENUM('초기화', '다음해로 이월'), nullable=False, comment='매 년 1월 1일기준'),
    sa.Column('account_based_less_than_year', mysql.ENUM('당해년도 일괄 부여', '매 월 1개씩 부여'), nullable=False, comment='근속년수 1년 미만'),
    sa.Column('account_based_decimal_point', mysql.ENUM('0.5 기준 올림', '절삭', '올림', '반올림'), nullable=False, comment='소수점처리'),
    sa.Column('entry_date_based_remaining_leave', mysql.ENUM('초기화', '다음해로 이월'), nullable=False, comment='매 년 입사일 기준'),
    sa.Column('condition_based_month', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition_based_cnt', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition_based_type', mysql.ENUM('월', '일'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_yn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='auto_annual_leave_grant_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('entry_date_based_annual_leave_grant')
    op.drop_table('condition_based_annual_leave_grant')
    op.drop_table('account_based_annual_leave_grant')
    # ### end Alembic commands ###
