"""salary_template_reseponse_fix

Revision ID: 52630b762d55
Revises: bbfd4bd27a3b
Create Date: 2024-10-24 22:30:56.142925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52630b762d55'
down_revision: Union[str, None] = 'bbfd4bd27a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_templates', sa.Column('holiday_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_templates', sa.Column('job_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_templates', sa.Column('meal_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_templates', sa.Column('hire_year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_templates', 'hire_year')
    op.drop_column('salary_templates', 'meal_allowance')
    op.drop_column('salary_templates', 'job_allowance')
    op.drop_column('salary_templates', 'holiday_allowance')
    # ### end Alembic commands ###
