"""message

Revision ID: 53125b349b1c
Revises: 8b423a8bfcd0
Create Date: 2024-10-12 17:18:34.922402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53125b349b1c'
down_revision: Union[str, None] = '8b423a8bfcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='roles')
    op.drop_table('roles')
    op.add_column('users', sa.Column('role', sa.Enum('MSO 최고권한', '최고관리자', '관리자', '사원', name='user_role'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.ENUM('MSO 최고권한', '최고관리자', '관리자', '사원'), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_yn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'roles', ['user_id'], unique=True)
    # ### end Alembic commands ###
