"""salary_template_model_fix

Revision ID: 5dbe36fa0061
Revises: 5cde4ffe5766
Create Date: 2024-10-24 16:27:38.988207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbe36fa0061'
down_revision: Union[str, None] = '5cde4ffe5766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commutes_id'), 'commutes', ['id'], unique=False)
    op.create_table('leave_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_category_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('approve_date', sa.Date(), nullable=True),
    sa.Column('applicant_description', sa.String(length=255), nullable=True),
    sa.Column('admin_description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('확인중', '승인', '반려', name='leave_history_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['leave_category_id'], ['leave_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'application_date', name='uq_user_application_date')
    )
    op.create_index('idx_leave_history_application_date', 'leave_histories', ['application_date'], unique=False)
    op.create_index('idx_leave_history_user_id', 'leave_histories', ['user_id'], unique=False)
    op.create_table('overtimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('overtime_hours', sa.Enum('30', '60', '90', '120', name='overtime_hours_options'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='overtime_status'), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('application_memo', sa.String(length=500), nullable=True),
    sa.Column('manager_memo', sa.String(length=500), nullable=True),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.Column('is_approved', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_menus',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('menu_name', sa.Enum('P.T관리', '계약관리(P.T)포함', '휴무관리', 'O.T관리', '인사관리', '근로관리', '급여정산', '문서설정관리', '휴직관리', '출퇴근기록관리'), nullable=False),
    sa.Column('is_permitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_parts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_salaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Float(), nullable=False),
    sa.Column('annual_salary', sa.Float(), nullable=False),
    sa.Column('hourly_wage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closed_days_closed_day_date'), 'closed_days', ['closed_day_date'], unique=False)
    op.create_index(op.f('ix_closed_days_id'), 'closed_days', ['id'], unique=False)
    op.add_column('salary_templates', sa.Column('holiday_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_templates', sa.Column('job_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_templates', sa.Column('meal_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_templates', sa.Column('hire_year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_templates', 'hire_year')
    op.drop_column('salary_templates', 'meal_allowance')
    op.drop_column('salary_templates', 'job_allowance')
    op.drop_column('salary_templates', 'holiday_allowance')
    op.drop_index(op.f('ix_closed_days_id'), table_name='closed_days')
    op.drop_index(op.f('ix_closed_days_closed_day_date'), table_name='closed_days')
    op.drop_table('user_salaries')
    op.drop_table('user_parts')
    op.drop_table('user_menus')
    op.drop_table('overtimes')
    op.drop_index('idx_leave_history_user_id', table_name='leave_histories')
    op.drop_index('idx_leave_history_application_date', table_name='leave_histories')
    op.drop_table('leave_histories')
    op.drop_index(op.f('ix_commutes_id'), table_name='commutes')
    op.drop_table('commutes')
    # ### end Alembic commands ###
