"""rds_통합본

Revision ID: 5f4e3fad13bb
Revises: 9dcacee2bd41
Create Date: 2024-10-26 21:07:08.850875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f4e3fad13bb'
down_revision: Union[str, None] = '9dcacee2bd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('contract_name', sa.String(length=255), nullable=False),
    sa.Column('contract_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contract_type_id'], ['document_policies.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_leaves_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('leave_category_id', sa.Integer(), nullable=False),
    sa.Column('increased_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('decreased_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('total_leave_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['leave_category_id'], ['leave_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_leaves_days_user_id', 'user_leaves_days', ['user_id'], unique=False)
    op.create_table('work_contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('is_fixed_rest_day', sa.Boolean(), nullable=False),
    sa.Column('weekly_work_hours', sa.Integer(), nullable=False),
    sa.Column('weekly_work_start_time', sa.Time(), nullable=False),
    sa.Column('weekly_is_rest', sa.Boolean(), nullable=False),
    sa.Column('saturday_work_hours', sa.Integer(), nullable=True),
    sa.Column('saturday_work_start_time', sa.Time(), nullable=True),
    sa.Column('saturday_is_rest', sa.Boolean(), nullable=False),
    sa.Column('sunday_work_hours', sa.Integer(), nullable=True),
    sa.Column('sunday_work_start_time', sa.Time(), nullable=True),
    sa.Column('sunday_is_rest', sa.Boolean(), nullable=False),
    sa.Column('is_part_timer', sa.Boolean(), nullable=False),
    sa.Column('break_start_time', sa.Time(), nullable=True),
    sa.Column('break_end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_rest_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_contract_id', sa.Integer(), nullable=False),
    sa.Column('rest_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=False),
    sa.Column('every_over_week', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_contract_id'], ['work_contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('overtimes', sa.Column('manager_name', sa.String(length=10), nullable=True))
    op.drop_column('salary_templates', 'deleted_yn')
    op.drop_column('salary_templates', 'updated_at')
    op.drop_column('salary_templates', 'created_at')
    op.add_column('users', sa.Column('total_leave_days', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('remaining_annual_leave', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_part_timer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_part_timer')
    op.drop_column('users', 'remaining_annual_leave')
    op.drop_column('users', 'total_leave_days')
    op.add_column('salary_templates', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('salary_templates', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('salary_templates', sa.Column('deleted_yn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True))
    op.drop_column('overtimes', 'manager_name')
    op.drop_table('fixed_rest_day')
    op.drop_table('work_contract')
    op.drop_index('idx_user_leaves_days_user_id', table_name='user_leaves_days')
    op.drop_table('user_leaves_days')
    op.drop_table('document')
    op.drop_table('contract')
    # ### end Alembic commands ###
