"""10.28_rds

Revision ID: 6d602294d5d9
Revises: 6bdb3d603431
Create Date: 2024-10-28 14:54:13.134414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d602294d5d9'
down_revision: Union[str, None] = '6bdb3d603431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overtime_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ot_30_total', sa.Integer(), nullable=True),
    sa.Column('ot_60_total', sa.Integer(), nullable=True),
    sa.Column('ot_90_total', sa.Integer(), nullable=True),
    sa.Column('ot_30_money', sa.Integer(), nullable=True),
    sa.Column('ot_60_money', sa.Integer(), nullable=True),
    sa.Column('ot_90_money', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_menus',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('menu_name', sa.Enum('P.T관리', '계약관리(P.T)포함', '휴무관리', 'O.T관리', '인사관리', '근로관리', '급여정산', '문서설정관리', '휴직관리', '출퇴근기록관리', name='menupermissions'), nullable=False),
    sa.Column('is_permitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_parts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_salaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Float(), nullable=False),
    sa.Column('annual_salary', sa.Float(), nullable=False),
    sa.Column('hourly_wage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('is_fixed_rest_day', sa.Boolean(), nullable=False),
    sa.Column('weekly_work_hours', sa.Integer(), nullable=False),
    sa.Column('weekly_work_start_time', sa.Time(), nullable=False),
    sa.Column('weekly_is_rest', sa.Boolean(), nullable=False),
    sa.Column('saturday_work_hours', sa.Integer(), nullable=True),
    sa.Column('saturday_work_start_time', sa.Time(), nullable=True),
    sa.Column('saturday_is_rest', sa.Boolean(), nullable=False),
    sa.Column('sunday_work_hours', sa.Integer(), nullable=True),
    sa.Column('sunday_work_start_time', sa.Time(), nullable=True),
    sa.Column('sunday_is_rest', sa.Boolean(), nullable=False),
    sa.Column('is_part_timer', sa.Boolean(), nullable=False),
    sa.Column('break_start_time', sa.Time(), nullable=True),
    sa.Column('break_end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_send_mail_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_user_id', sa.Integer(), nullable=False),
    sa.Column('contract_send_mail_history_status', sa.Enum('SUCCESS', 'FAIL', name='status'), nullable=False),
    sa.Column('contract_start_at', sa.Date(), nullable=False),
    sa.Column('contract_expired_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['request_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_send_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_user_id', sa.Integer(), nullable=False),
    sa.Column('document_send_history_status', sa.Enum('PENDING', 'APPROVE', 'REJECT', name='documentsendstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['request_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_rest_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_contract_id', sa.Integer(), nullable=False),
    sa.Column('rest_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=False),
    sa.Column('every_over_week', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_contract_id'], ['work_contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('allowance_policies', sa.Column('job_allowance', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('allowance_policies', sa.Column('meal_allowance', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('contract', sa.Column('start_at', sa.Date(), nullable=False))
    op.add_column('leave_histories', sa.Column('decreased_days', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('salary_templates', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('salary_templates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('salary_templates', sa.Column('deleted_yn', sa.String(length=1), nullable=True))
    op.drop_column('salary_templates', 'holiday_allowance')
    op.drop_column('salary_templates', 'job_allowance')
    op.drop_column('salary_templates', 'meal_allowance')
    op.drop_column('salary_templates', 'part_name')
    op.add_column('user_leaves_days', sa.Column('leave_history_id', sa.Integer(), nullable=False))
    op.add_column('user_leaves_days', sa.Column('total_increased_days', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('user_leaves_days', sa.Column('total_decreased_days', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('user_leaves_days', 'increased_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('user_leaves_days', 'decreased_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('user_leaves_days', 'total_leave_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.create_foreign_key(None, 'user_leaves_days', 'leave_histories', ['leave_history_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_leaves_days', type_='foreignkey')
    op.alter_column('user_leaves_days', 'total_leave_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('user_leaves_days', 'decreased_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('user_leaves_days', 'increased_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_column('user_leaves_days', 'total_decreased_days')
    op.drop_column('user_leaves_days', 'total_increased_days')
    op.drop_column('user_leaves_days', 'leave_history_id')
    op.add_column('salary_templates', sa.Column('part_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('salary_templates', sa.Column('meal_allowance', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('salary_templates', sa.Column('job_allowance', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('salary_templates', sa.Column('holiday_allowance', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('salary_templates', 'deleted_yn')
    op.drop_column('salary_templates', 'updated_at')
    op.drop_column('salary_templates', 'created_at')
    op.drop_column('leave_histories', 'decreased_days')
    op.drop_column('contract', 'start_at')
    op.drop_column('allowance_policies', 'meal_allowance')
    op.drop_column('allowance_policies', 'job_allowance')
    op.drop_table('fixed_rest_day')
    op.drop_table('document_send_history')
    op.drop_table('contract_send_mail_history')
    op.drop_table('work_contract')
    op.drop_table('user_salaries')
    op.drop_table('user_parts')
    op.drop_table('user_menus')
    op.drop_table('overtime_history')
    # ### end Alembic commands ###
