"""v15

Revision ID: 803f44e21b40
Revises: cfc0a931ae9c
Create Date: 2024-11-04 09:34:50.770996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803f44e21b40'
down_revision: Union[str, None] = 'cfc0a931ae9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_application_date', table_name='leave_histories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_user_application_date', 'leave_histories', ['user_id', 'application_date'], unique=True)
    # ### end Alembic commands ###
