"""10_28_1158

Revision ID: 81496fbeb00d
Revises: 86f80abd758c
Create Date: 2024-10-28 11:59:03.008974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81496fbeb00d'
down_revision: Union[str, None] = '86f80abd758c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_send_mail_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_user_id', sa.Integer(), nullable=False),
    sa.Column('contract_send_mail_history_status', sa.Enum('SUCCESS', 'FAIL', name='status'), nullable=False),
    sa.Column('contract_start_at', sa.Date(), nullable=False),
    sa.Column('contract_expired_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['request_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_send_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_user_id', sa.Integer(), nullable=False),
    sa.Column('document_send_history_status', sa.Enum('PENDING', 'APPROVE', 'REJECT', name='documentsendstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['request_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('allowance_policies', sa.Column('job_allowance', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('allowance_policies', sa.Column('meal_allowance', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('contract', sa.Column('start_at', sa.Date(), nullable=False))
    op.add_column('leave_histories', sa.Column('decreased_days', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('salary_templates', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('salary_templates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('salary_templates', sa.Column('deleted_yn', sa.String(length=1), nullable=True))
    op.drop_column('salary_templates', 'part_name')
    op.drop_column('salary_templates', 'holiday_allowance')
    op.drop_column('salary_templates', 'meal_allowance')
    op.drop_column('salary_templates', 'job_allowance')
    op.add_column('user_leaves_days', sa.Column('leave_history_id', sa.Integer(), nullable=False))
    op.add_column('user_leaves_days', sa.Column('total_increased_days', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('user_leaves_days', sa.Column('total_decreased_days', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('user_leaves_days', 'increased_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('user_leaves_days', 'decreased_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('user_leaves_days', 'total_leave_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.create_foreign_key(None, 'user_leaves_days', 'leave_histories', ['leave_history_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_leaves_days', type_='foreignkey')
    op.alter_column('user_leaves_days', 'total_leave_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('user_leaves_days', 'decreased_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('user_leaves_days', 'increased_days',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_column('user_leaves_days', 'total_decreased_days')
    op.drop_column('user_leaves_days', 'total_increased_days')
    op.drop_column('user_leaves_days', 'leave_history_id')
    op.add_column('salary_templates', sa.Column('job_allowance', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('salary_templates', sa.Column('meal_allowance', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('salary_templates', sa.Column('holiday_allowance', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('salary_templates', sa.Column('part_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_column('salary_templates', 'deleted_yn')
    op.drop_column('salary_templates', 'updated_at')
    op.drop_column('salary_templates', 'created_at')
    op.drop_column('leave_histories', 'decreased_days')
    op.drop_column('contract', 'start_at')
    op.drop_column('allowance_policies', 'meal_allowance')
    op.drop_column('allowance_policies', 'job_allowance')
    op.drop_table('document_send_history')
    op.drop_table('contract_send_mail_history')
    # ### end Alembic commands ###
