"""v3

Revision ID: 85126e30108c
Revises: 2d6aa8b25a6e
Create Date: 2024-10-29 15:34:22.940016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85126e30108c'
down_revision: Union[str, None] = '2d6aa8b25a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parttimer_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('weekday_base_salary', sa.Boolean(), nullable=True),
    sa.Column('remote_base_salary', sa.Boolean(), nullable=True),
    sa.Column('annual_leave_allowance', sa.Boolean(), nullable=True),
    sa.Column('overtime_allowance', sa.Boolean(), nullable=True),
    sa.Column('holiday_work_allowance', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_templates_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('unused_annual_leave_allowance', sa.Boolean(), nullable=True),
    sa.Column('additional_overtime_allowance', sa.Boolean(), nullable=True),
    sa.Column('additional_holiday_allowance', sa.Boolean(), nullable=True),
    sa.Column('annual_leave_deduction', sa.Boolean(), nullable=True),
    sa.Column('attendance_deduction', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id')
    )
    op.create_table('branch_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('history_type', sa.Enum('AUTO_ANNUAL_LEAVE_GRANT', name='branchhistorytype'), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_histories_history_type'), 'branch_histories', ['history_type'], unique=False)
    op.add_column('allowance_policies', sa.Column('payment_day', sa.Integer(), nullable=False))
    op.add_column('allowance_policies', sa.Column('base_salary', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('employment_status', sa.Enum('정규직', '계약직', name='employment_status'), nullable=False))
    op.drop_column('users', 'is_part_timer')
    op.add_column('work_contract', sa.Column('weekly_work_end_time', sa.Time(), nullable=False))
    op.add_column('work_contract', sa.Column('saturday_work_end_time', sa.Time(), nullable=True))
    op.add_column('work_contract', sa.Column('sunday_work_end_time', sa.Time(), nullable=True))
    op.drop_column('work_contract', 'is_part_timer')
    op.drop_column('work_contract', 'weekly_work_hours')
    op.drop_column('work_contract', 'saturday_work_hours')
    op.drop_column('work_contract', 'sunday_work_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_contract', sa.Column('sunday_work_hours', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('work_contract', sa.Column('saturday_work_hours', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('work_contract', sa.Column('weekly_work_hours', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('work_contract', sa.Column('is_part_timer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('work_contract', 'sunday_work_end_time')
    op.drop_column('work_contract', 'saturday_work_end_time')
    op.drop_column('work_contract', 'weekly_work_end_time')
    op.add_column('users', sa.Column('is_part_timer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('users', 'employment_status')
    op.drop_column('allowance_policies', 'base_salary')
    op.drop_column('allowance_policies', 'payment_day')
    op.drop_index(op.f('ix_branch_histories_history_type'), table_name='branch_histories')
    op.drop_table('branch_histories')
    op.drop_table('salary_templates_policies')
    op.drop_table('parttimer_policies')
    # ### end Alembic commands ###
