"""10.28_rds

Revision ID: 860279e01446
Revises: 
Create Date: 2024-10-28 14:43:16.139253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860279e01446'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_table_safe(name: str, *args, **kwargs) -> None:
   try:
       op.create_table(name, *args, **kwargs)
   except Exception as e:
       print(f"{name} 테이블 생성 스킵: {e}")

def create_index_safe(name: str, table: str, columns: list, **kwargs) -> None:
   try:
       op.create_index(name, table, columns, **kwargs)
   except Exception as e:
       print(f"{name} 인덱스 생성 스킵: {e}")

def upgrade() -> None:
   # ### commands auto generated by Alembic - please adjust! ###
   create_table_safe('branches',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('code', sa.String(length=255), nullable=False),
       sa.Column('name', sa.String(length=255), nullable=False),
       sa.Column('representative_name', sa.String(length=255), nullable=False),
       sa.Column('registration_number', sa.String(length=255), nullable=False),
       sa.Column('call_number', sa.String(length=255), nullable=False),
       sa.Column('address', sa.String(length=255), nullable=False),
       sa.Column('corporate_seal', sa.String(length=255), nullable=True),
       sa.Column('nameplate', sa.String(length=255), nullable=True),
       sa.Column('mail_address', sa.String(length=255), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.PrimaryKeyConstraint('id')
   )
   
   create_table_safe('minimum_wage_policies',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('minimum_wage', sa.Integer(), nullable=False),
       sa.Column('person_in_charge', sa.String(length=255), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.PrimaryKeyConstraint('id')
   )
   
   create_table_safe('salary_brackets',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('year', sa.Integer(), nullable=False),
       sa.Column('minimum_hourly_rate', sa.Float(), nullable=False),
       sa.Column('minimum_monthly_rate', sa.Float(), nullable=False),
       sa.Column('national_pension', sa.Float(), nullable=False),
       sa.Column('health_insurance', sa.Float(), nullable=False),
       sa.Column('employment_insurance', sa.Float(), nullable=False),
       sa.Column('long_term_care_insurance', sa.Float(), nullable=False),
       sa.Column('minimum_pension_income', sa.Float(), nullable=False),
       sa.Column('maximum_pension_income', sa.Float(), nullable=False),
       sa.Column('maximum_national_pension', sa.Float(), nullable=False),
       sa.Column('minimum_health_insurance', sa.Float(), nullable=False),
       sa.Column('maximum_health_insurance', sa.Float(), nullable=False),
       sa.Column('local_income_tax_rate', sa.Float(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.PrimaryKeyConstraint('id')
   )
   
   create_table_safe('allowance_policies',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('comprehensive_overtime', sa.Boolean(), nullable=True),
       sa.Column('annual_leave', sa.Boolean(), nullable=True),
       sa.Column('holiday_work', sa.Boolean(), nullable=True),
       sa.Column('job_duty', sa.Boolean(), nullable=True),
       sa.Column('meal', sa.Boolean(), nullable=True),
       sa.Column('job_allowance', sa.Integer(), server_default=sa.text('0'), nullable=True),
       sa.Column('meal_allowance', sa.Integer(), server_default=sa.text('0'), nullable=True),
       sa.Column('doctor_holiday_work_pay', sa.Integer(), nullable=False),
       sa.Column('common_holiday_work_pay', sa.Integer(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )
   
   create_table_safe('auto_annual_leave_approval',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('top_auto_approval', sa.Boolean(), nullable=True),
       sa.Column('total_auto_approval', sa.Boolean(), nullable=True),
       sa.Column('part_auto_approval', sa.Boolean(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )
   
   create_table_safe('auto_annual_leave_grant',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('account_based_january_1st', sa.Enum('초기화', '다음해로 이월'), nullable=False, comment='매 년 1월 1일기준'),
       sa.Column('account_based_less_than_year', sa.Enum('당해년도 일괄 부여', '매 월 1개씩 부여'), nullable=False, comment='근속년수 1년 미만'),
       sa.Column('account_based_decimal_point', sa.Enum('0.5 기준 올림', '절삭', '올림', '반올림'), nullable=False, comment='소수점처리'),
       sa.Column('entry_date_based_remaining_leave', sa.Enum('초기화', '다음해로 이월'), nullable=False, comment='매 년 입사일 기준'),
       sa.Column('condition_based_month', sa.Integer(), nullable=False),
       sa.Column('condition_based_cnt', sa.Integer(), nullable=False),
       sa.Column('condition_based_type', sa.Enum('월', '일'), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )
   
   create_table_safe('auto_overtime_policies',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('top_auto_applied', sa.Boolean(), nullable=True),
       sa.Column('total_auto_applied', sa.Boolean(), nullable=True),
       sa.Column('part_auto_applied', sa.Boolean(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )
       
   create_table_safe('commute_policies',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('do_commute', sa.Boolean(), nullable=True),
       sa.Column('allowed_ip_commute', sa.String(length=255), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('document_policies',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('document_type', sa.String(length=255), nullable=False),
       sa.Column('can_view', sa.Boolean(), nullable=True),
       sa.Column('can_edit', sa.Boolean(), nullable=True),
       sa.Column('can_delete', sa.Boolean(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('holiday_work_policies',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('do_holiday_work', sa.Boolean(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('leave_categories',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('name', sa.String(length=255), nullable=False),
       sa.Column('leave_count', sa.Integer(), nullable=False),
       sa.Column('is_paid', sa.Boolean(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('overtime_policies',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('doctor_ot_30', sa.Integer(), nullable=False),
       sa.Column('doctor_ot_60', sa.Integer(), nullable=False),
       sa.Column('doctor_ot_90', sa.Integer(), nullable=False),
       sa.Column('doctor_ot_120', sa.Integer(), nullable=False),
       sa.Column('common_ot_30', sa.Integer(), nullable=False),
       sa.Column('common_ot_60', sa.Integer(), nullable=False),
       sa.Column('common_ot_90', sa.Integer(), nullable=False),
       sa.Column('common_ot_120', sa.Integer(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('parts',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('name', sa.String(length=255), nullable=False),
       sa.Column('task', sa.String(length=500), nullable=True),
       sa.Column('color', sa.String(length=255), nullable=True),
       sa.Column('is_doctor', sa.Boolean(), nullable=True),
       sa.Column('required_certification', sa.Boolean(), nullable=True),
       sa.Column('leave_granting_authority', sa.Boolean(), nullable=True),
       sa.Column('auto_annual_leave_grant', sa.Enum('수동부여', '회계기준 부여', '입사일 기준 부여', '조건별 부여', name='part_auto_annual_leave_grant'), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('rest_days',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('date', sa.Date(), nullable=False),
       sa.Column('rest_type', sa.Enum('공휴일', '주말', name='rest_day_type'), nullable=False),
       sa.Column('description', sa.String(length=255), nullable=True),
       sa.Column('is_paid', sa.Boolean(), nullable=True),
       sa.Column('is_holiday_work_allowed', sa.Boolean(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id'),
       sa.UniqueConstraint('branch_id', 'date', name='uq_branch_part_date')
   )
   
   create_index_safe('idx_rest_days_branch_id', 'rest_days', ['branch_id'], unique=False)
   create_index_safe('idx_rest_days_date', 'rest_days', ['date'], unique=False)
    ##
   create_table_safe('tax_brackets',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('salary_bracket_id', sa.Integer(), nullable=False),
       sa.Column('lower_limit', sa.Float(), nullable=False),
       sa.Column('upper_limit', sa.Float(), nullable=True),
       sa.Column('tax_rate', sa.Float(), nullable=False),
       sa.Column('deduction', sa.Float(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['salary_bracket_id'], ['salary_brackets.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('work_policies',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('weekly_work_days', sa.Integer(), nullable=False),
       sa.Column('weekday_start_time', sa.Time(), nullable=False),
       sa.Column('weekday_end_time', sa.Time(), nullable=False),
       sa.Column('weekday_is_holiday', sa.Boolean(), nullable=True),
       sa.Column('saturday_start_time', sa.Time(), nullable=True),
       sa.Column('saturday_end_time', sa.Time(), nullable=True),
       sa.Column('saturday_is_holiday', sa.Boolean(), nullable=True),
       sa.Column('sunday_start_time', sa.Time(), nullable=True),
       sa.Column('sunday_end_time', sa.Time(), nullable=True),
       sa.Column('sunday_is_holiday', sa.Boolean(), nullable=True),
       sa.Column('doctor_lunch_start_time', sa.Time(), nullable=True),
       sa.Column('doctor_lunch_end_time', sa.Time(), nullable=True),
       sa.Column('doctor_dinner_start_time', sa.Time(), nullable=True),
       sa.Column('doctor_dinner_end_time', sa.Time(), nullable=True),
       sa.Column('common_lunch_start_time', sa.Time(), nullable=True),
       sa.Column('common_lunch_end_time', sa.Time(), nullable=True),
       sa.Column('common_dinner_start_time', sa.Time(), nullable=True),
       sa.Column('common_dinner_end_time', sa.Time(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('hour_wage_templates',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('part_id', sa.Integer(), nullable=True),
       sa.Column('name', sa.String(length=255), nullable=False),
       sa.Column('start_time', sa.Time(), nullable=False),
       sa.Column('end_time', sa.Time(), nullable=False),
       sa.Column('hour_wage', sa.Integer(), nullable=False),
       sa.Column('home_hour_wage', sa.Integer(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('leave_excluded_parts',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('leave_category_id', sa.Integer(), nullable=False),
       sa.Column('part_id', sa.Integer(), nullable=False),
       sa.ForeignKeyConstraint(['leave_category_id'], ['leave_categories.id'], ),
       sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('salary_policies',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('part_id', sa.Integer(), nullable=False),
       sa.Column('base_salary', sa.Integer(), nullable=True),
       sa.Column('annual_leave_days', sa.Integer(), nullable=True),
       sa.Column('sick_leave_days', sa.Integer(), nullable=True),
       sa.Column('overtime_rate', sa.Float(), nullable=True),
       sa.Column('night_work_allowance', sa.Integer(), nullable=True),
       sa.Column('holiday_work_allowance', sa.Integer(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('salary_templates',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('part_id', sa.Integer(), nullable=False),
       sa.Column('name', sa.String(length=255), nullable=False),
       sa.Column('is_january_entry', sa.Boolean(), nullable=False),
       sa.Column('weekly_work_days', sa.Integer(), nullable=False),
       sa.Column('month_salary', sa.Integer(), nullable=False),
       sa.Column('included_holiday_allowance', sa.Boolean(), nullable=False),
       sa.Column('included_job_allowance', sa.Boolean(), nullable=False),
       sa.Column('hour_wage', sa.Integer(), nullable=False),
       sa.Column('basic_salary', sa.Integer(), nullable=False),
       sa.Column('contractual_working_hours', sa.Integer(), nullable=False),
       sa.Column('weekly_rest_hours', sa.Integer(), nullable=False),
       sa.Column('annual_salary', sa.Integer(), nullable=False),
       sa.Column('comprehensive_overtime_allowance', sa.Integer(), nullable=False),
       sa.Column('comprehensive_overtime_hour', sa.Integer(), nullable=False),
       sa.Column('annual_leave_allowance', sa.Integer(), nullable=False),
       sa.Column('annual_leave_allowance_hour', sa.Integer(), nullable=False),
       sa.Column('annual_leave_allowance_day', sa.Integer(), nullable=False),
       sa.Column('hire_year', sa.Integer(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('users',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('name', sa.String(length=255), nullable=False),
       sa.Column('email', sa.String(length=255), nullable=False),
       sa.Column('password', sa.String(length=255), nullable=False),
       sa.Column('phone_number', sa.String(length=20), nullable=True),
       sa.Column('address', sa.String(length=500), nullable=True),
       sa.Column('education', sa.String(length=255), nullable=True),
       sa.Column('birth_date', sa.Date(), nullable=True),
       sa.Column('hire_date', sa.Date(), nullable=True),
       sa.Column('resignation_date', sa.Date(), nullable=True),
       sa.Column('total_leave_days', sa.Numeric(precision=10, scale=2), nullable=True),
       sa.Column('gender', sa.Enum('남자', '여자', name='user_gender'), nullable=False),
       sa.Column('part_id', sa.Integer(), nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('remaining_annual_leave', sa.Integer(), nullable=True),
       sa.Column('last_company', sa.String(length=255), nullable=True),
       sa.Column('last_position', sa.String(length=255), nullable=True),
       sa.Column('last_career_start_date', sa.Date(), nullable=True),
       sa.Column('last_career_end_date', sa.Date(), nullable=True),
       sa.Column('role', sa.Enum('MSO 최고권한', '최고관리자', '통합관리자', '관리자', '사원', '퇴사자', '휴직자', name='user_role'), nullable=False),
       sa.Column('is_part_timer', sa.Boolean(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
       sa.PrimaryKeyConstraint('id'),
       sa.UniqueConstraint('email')
   )

   create_table_safe('closed_days',
       sa.Column('id', sa.Integer(), nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=True),
       sa.Column('part_id', sa.Integer(), nullable=True),
       sa.Column('user_id', sa.Integer(), nullable=True),
       sa.Column('closed_day_date', sa.Date(), nullable=False),
       sa.Column('memo', sa.String(length=500), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_index_safe(op.f('ix_closed_days_branch_id'), 'closed_days', ['branch_id'], unique=False)
   create_index_safe(op.f('ix_closed_days_closed_day_date'), 'closed_days', ['closed_day_date'], unique=False)
   create_index_safe(op.f('ix_closed_days_id'), 'closed_days', ['id'], unique=False)

   create_table_safe('commutes',
       sa.Column('id', sa.Integer(), nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('clock_in', sa.DateTime(), nullable=False),
       sa.Column('clock_out', sa.DateTime(), nullable=True),
       sa.Column('work_hours', sa.Float(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_index_safe(op.f('ix_commutes_id'), 'commutes', ['id'], unique=False)

   create_table_safe('contract',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('manager_id', sa.Integer(), nullable=False),
       sa.Column('contract_name', sa.String(length=255), nullable=False),
       sa.Column('contract_type_id', sa.Integer(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('start_at', sa.Date(), nullable=False),
       sa.Column('expired_at', sa.Date(), nullable=True),
       sa.ForeignKeyConstraint(['contract_type_id'], ['document_policies.id'], ),
       sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('document',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('document_name', sa.String(length=255), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('leave_histories',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('leave_category_id', sa.Integer(), nullable=False),
       sa.Column('decreased_days', sa.Numeric(precision=10, scale=2), nullable=True),
       sa.Column('application_date', sa.Date(), nullable=False),
       sa.Column('approve_date', sa.Date(), nullable=True),
       sa.Column('applicant_description', sa.String(length=255), nullable=True),
       sa.Column('admin_description', sa.String(length=255), nullable=True),
       sa.Column('status', sa.Enum('확인중', '승인', '반려', name='leave_history_status'), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.ForeignKeyConstraint(['leave_category_id'], ['leave_categories.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id'),
       sa.UniqueConstraint('user_id', 'application_date', name='uq_user_application_date')
   )

   create_index_safe('idx_leave_history_application_date', 'leave_histories', ['application_date'], unique=False)
   create_index_safe('idx_leave_history_user_id', 'leave_histories', ['user_id'], unique=False)

   create_table_safe('overtime_history',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('ot_30_total', sa.Integer(), nullable=True),
       sa.Column('ot_60_total', sa.Integer(), nullable=True),
       sa.Column('ot_90_total', sa.Integer(), nullable=True),
       sa.Column('ot_30_money', sa.Integer(), nullable=True),
       sa.Column('ot_60_money', sa.Integer(), nullable=True),
       sa.Column('ot_90_money', sa.Integer(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_at', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('overtimes',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('applicant_id', sa.Integer(), nullable=False),
       sa.Column('manager_id', sa.Integer(), nullable=True),
       sa.Column('manager_name', sa.String(length=10), nullable=True),
       sa.Column('overtime_hours', sa.Enum('30', '60', '90', '120', name='overtime_hours_options'), nullable=False),
       sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='overtime_status'), nullable=False),
       sa.Column('application_date', sa.Date(), nullable=False),
       sa.Column('application_memo', sa.String(length=500), nullable=True),
       sa.Column('manager_memo', sa.String(length=500), nullable=True),
       sa.Column('processed_date', sa.Date(), nullable=True),
       sa.Column('is_approved', sa.String(length=1), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
       sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('user_menus',
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('part_id', sa.Integer(), nullable=False),
       sa.Column('menu_name', sa.Enum('P.T관리', '계약관리(P.T)포함', '휴무관리', 'O.T관리', '인사관리', '근로관리', '급여정산', '문서설정관리', '휴직관리', '출퇴근기록관리', name='menupermissions'), nullable=False),
       sa.Column('is_permitted', sa.Boolean(), nullable=True),
       sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
   )

   create_table_safe('user_parts',
       sa.Column('user_id', sa.Integer(), nullable=True),
       sa.Column('part_id', sa.Integer(), nullable=True),
       sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
   )

   create_table_safe('user_salaries',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('part_id', sa.Integer(), nullable=False),
       sa.Column('monthly_salary', sa.Float(), nullable=False),
       sa.Column('annual_salary', sa.Float(), nullable=False),
       sa.Column('hourly_wage', sa.Float(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('work_contract',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=True),
       sa.Column('contract_start_date', sa.Date(), nullable=False),
       sa.Column('contract_end_date', sa.Date(), nullable=True),
       sa.Column('is_fixed_rest_day', sa.Boolean(), nullable=False),
       sa.Column('weekly_work_hours', sa.Integer(), nullable=False),
       sa.Column('weekly_work_start_time', sa.Time(), nullable=False),
       sa.Column('weekly_is_rest', sa.Boolean(), nullable=False),
       sa.Column('saturday_work_hours', sa.Integer(), nullable=True),
       sa.Column('saturday_work_start_time', sa.Time(), nullable=True),
       sa.Column('saturday_is_rest', sa.Boolean(), nullable=False),
       sa.Column('sunday_work_hours', sa.Integer(), nullable=True),
       sa.Column('sunday_work_start_time', sa.Time(), nullable=True),
       sa.Column('sunday_is_rest', sa.Boolean(), nullable=False),
       sa.Column('is_part_timer', sa.Boolean(), nullable=False),
       sa.Column('break_start_time', sa.Time(), nullable=True),
       sa.Column('break_end_time', sa.Time(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('contract_send_mail_history',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('contract_id', sa.Integer(), nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('request_user_id', sa.Integer(), nullable=False),
       sa.Column('contract_send_mail_history_status', sa.Enum('SUCCESS', 'FAIL', name='status'), nullable=False),
       sa.Column('contract_start_at', sa.Date(), nullable=False),
       sa.Column('contract_expired_at', sa.Date(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
       sa.ForeignKeyConstraint(['request_user_id'], ['users.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('document_send_history',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('document_id', sa.Integer(), nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('request_user_id', sa.Integer(), nullable=False),
       sa.Column('document_send_history_status', sa.Enum('PENDING', 'APPROVE', 'REJECT', name='documentsendstatus'), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
       sa.ForeignKeyConstraint(['request_user_id'], ['users.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('fixed_rest_day',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('work_contract_id', sa.Integer(), nullable=False),
       sa.Column('rest_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=False),
       sa.Column('every_over_week', sa.Boolean(), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.ForeignKeyConstraint(['work_contract_id'], ['work_contract.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_table_safe('user_leaves_days',
       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
       sa.Column('user_id', sa.Integer(), nullable=False),
       sa.Column('branch_id', sa.Integer(), nullable=False),
       sa.Column('approver_id', sa.Integer(), nullable=True),
       sa.Column('leave_category_id', sa.Integer(), nullable=False),
       sa.Column('leave_history_id', sa.Integer(), nullable=False),
       sa.Column('increased_days', sa.Numeric(precision=10, scale=2), nullable=False),
       sa.Column('total_increased_days', sa.Numeric(precision=10, scale=2), nullable=False),
       sa.Column('decreased_days', sa.Numeric(precision=10, scale=2), nullable=False),
       sa.Column('total_decreased_days', sa.Numeric(precision=10, scale=2), nullable=False),
       sa.Column('description', sa.String(length=255), nullable=True),
       sa.Column('is_paid', sa.Boolean(), nullable=True),
       sa.Column('is_approved', sa.Boolean(), nullable=True),
       sa.Column('total_leave_days', sa.Numeric(precision=10, scale=2), nullable=False),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('deleted_yn', sa.String(length=1), nullable=True),
       sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
       sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
       sa.ForeignKeyConstraint(['leave_category_id'], ['leave_categories.id'], ),
       sa.ForeignKeyConstraint(['leave_history_id'], ['leave_histories.id'], ),
       sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
       sa.PrimaryKeyConstraint('id')
   )

   create_index_safe('idx_user_leaves_days_user_id', 'user_leaves_days', ['user_id'], unique=False)
   # ### end Alembic commands ###


def downgrade() -> None:
   # ### commands auto generated by Alembic - please adjust! ###
   op.drop_index('idx_user_leaves_days_user_id', table_name='user_leaves_days')
   op.drop_table('user_leaves_days')
   op.drop_table('fixed_rest_day')
   op.drop_table('document_send_history')
   op.drop_table('contract_send_mail_history')
   op.drop_table('work_contract')
   op.drop_table('user_salaries')
   op.drop_table('user_parts')
   op.drop_table('user_menus')
   op.drop_table('overtimes')
   op.drop_table('overtime_history')
   op.drop_index('idx_leave_history_user_id', table_name='leave_histories')
   op.drop_index('idx_leave_history_application_date', table_name='leave_histories')
   op.drop_table('leave_histories')
   op.drop_table('document')
   op.drop_table('contract')
   op.drop_index(op.f('ix_commutes_id'), table_name='commutes')
   op.drop_table('commutes')
   op.drop_index(op.f('ix_closed_days_id'), table_name='closed_days')
   op.drop_index(op.f('ix_closed_days_closed_day_date'), table_name='closed_days')
   op.drop_index(op.f('ix_closed_days_branch_id'), table_name='closed_days')
   op.drop_table('closed_days')
   op.drop_table('users')
   op.drop_table('salary_templates')
   op.drop_table('salary_policies')
   op.drop_table('leave_excluded_parts')
   op.drop_table('hour_wage_templates')
   op.drop_table('work_policies')
   op.drop_table('tax_brackets')
   op.drop_index('idx_rest_days_date', table_name='rest_days')
   op.drop_index('idx_rest_days_branch_id', table_name='rest_days')
   op.drop_table('rest_days')
   op.drop_table('parts')
   op.drop_table('overtime_policies')
   op.drop_table('leave_categories')
   op.drop_table('holiday_work_policies')
   op.drop_table('document_policies')
   op.drop_table('commute_policies')
   op.drop_table('auto_overtime_policies')
   op.drop_table('auto_annual_leave_grant')
   op.drop_table('auto_annual_leave_approval')
   op.drop_table('allowance_policies')
   op.drop_table('tax_brackets')
   op.drop_table('salary_brackets')
   op.drop_table('minimum_wage_policies')
   op.drop_table('branches')
   # ### end Alembic commands ###