"""v12

Revision ID: 87465d637550
Revises: 97278b88c354
Create Date: 2024-11-02 16:17:46.847125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87465d637550'
down_revision: Union[str, None] = '97278b88c354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('early_clock_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('early_clock_in', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_early_clock_in_early_clock_in'), 'early_clock_in', ['early_clock_in'], unique=False)
    op.create_index(op.f('ix_early_clock_in_id'), 'early_clock_in', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_early_clock_in_id'), table_name='early_clock_in')
    op.drop_index(op.f('ix_early_clock_in_early_clock_in'), table_name='early_clock_in')
    op.drop_table('early_clock_in')
    # ### end Alembic commands ###
