"""Update all models including policies

Revision ID: 8b423a8bfcd0
Revises: c7e0eeb430fd
Create Date: 2024-10-12 15:26:09.281033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b423a8bfcd0'
down_revision: Union[str, None] = 'c7e0eeb430fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.Enum('근태', '직책', '상담실적', '의사', '예산', name='policy_type'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_policy_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_policy_id'], ['branch_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_policy_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('policy_details', sa.String(length=500), nullable=True),
    sa.Column('structure', sa.String(length=255), nullable=True),
    sa.Column('group', sa.String(length=255), nullable=True),
    sa.Column('auto_calculation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_policy_id'], ['branch_policies.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_policy_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('annual_leave_days', sa.Integer(), nullable=False),
    sa.Column('sick_leave_days', sa.Integer(), nullable=False),
    sa.Column('overtime_rate', sa.Float(), nullable=False),
    sa.Column('night_work_allowance', sa.Integer(), nullable=False),
    sa.Column('holiday_work_allowance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_policy_id'], ['branch_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_policy_id', sa.Integer(), nullable=False),
    sa.Column('work_start_time', sa.DateTime(), nullable=False),
    sa.Column('work_end_time', sa.DateTime(), nullable=False),
    sa.Column('lunch_start_time', sa.DateTime(), nullable=False),
    sa.Column('lunch_end_time', sa.DateTime(), nullable=False),
    sa.Column('break_time_1', sa.String(length=50), nullable=True),
    sa.Column('break_time_2', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_policy_id'], ['branch_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_salary_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('salary_policy_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=True),
    sa.Column('annual_leave_days', sa.Integer(), nullable=True),
    sa.Column('sick_leave_days', sa.Integer(), nullable=True),
    sa.Column('overtime_rate', sa.Float(), nullable=True),
    sa.Column('night_work_allowance', sa.Integer(), nullable=True),
    sa.Column('holiday_work_allowance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['salary_policy_id'], ['salary_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_work_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('work_policy_id', sa.Integer(), nullable=False),
    sa.Column('work_start_time', sa.DateTime(), nullable=True),
    sa.Column('work_end_time', sa.DateTime(), nullable=True),
    sa.Column('lunch_start_time', sa.DateTime(), nullable=True),
    sa.Column('lunch_end_time', sa.DateTime(), nullable=True),
    sa.Column('break_time_1', sa.String(length=50), nullable=True),
    sa.Column('break_time_2', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['work_policy_id'], ['work_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part_work_policies')
    op.drop_table('part_salary_policies')
    op.drop_table('work_policies')
    op.drop_table('salary_policies')
    op.drop_table('part_policies')
    op.drop_table('document_policies')
    op.drop_table('branch_policies')
    # ### end Alembic commands ###
