"""v4

Revision ID: 8c82b2e1a98d
Revises: 85126e30108c
Create Date: 2024-10-30 14:47:12.931962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c82b2e1a98d'
down_revision: Union[str, None] = '85126e30108c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel_record_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_timer_work_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_start_date', sa.Date(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_timer_additional_infos',
    sa.Column('commute_id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.Enum('HOSPITAL', 'REMOTE', 'HOLIDAY', name='worktypeenum'), nullable=False),
    sa.Column('rest_minutes', sa.Integer(), nullable=False),
    sa.Column('work_set_start_time', sa.Time(), nullable=False),
    sa.Column('work_set_end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['commute_id'], ['commutes.id'], ),
    sa.PrimaryKeyConstraint('commute_id')
    )
    op.create_table('part_timer_hourly_wages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_timer_work_contract_id', sa.Integer(), nullable=False),
    sa.Column('calculate_start_time', sa.Time(), nullable=False),
    sa.Column('calculate_end_time', sa.Time(), nullable=False),
    sa.Column('hourly_wage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_timer_work_contract_id'], ['part_timer_work_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_timer_working_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_timer_work_contract_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('work_start_time', sa.Time(), nullable=False),
    sa.Column('work_end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['part_timer_work_contract_id'], ['part_timer_work_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('allowance_policies', sa.Column('is_additional_holiday_hundred', sa.Boolean(), nullable=True))
    op.add_column('allowance_policies', sa.Column('is_unused_annual_leave_hundred', sa.Boolean(), nullable=True))
    op.add_column('allowance_policies', sa.Column('is_annual_leave_deduction_hundred', sa.Boolean(), nullable=True))
    op.add_column('allowance_policies', sa.Column('is_attendance_deduction_hundred', sa.Boolean(), nullable=True))
    op.add_column('allowance_policies', sa.Column('display_meal_calc', sa.Boolean(), nullable=True))
    op.add_column('allowance_policies', sa.Column('display_night_calc', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allowance_policies', 'display_night_calc')
    op.drop_column('allowance_policies', 'display_meal_calc')
    op.drop_column('allowance_policies', 'is_attendance_deduction_hundred')
    op.drop_column('allowance_policies', 'is_annual_leave_deduction_hundred')
    op.drop_column('allowance_policies', 'is_unused_annual_leave_hundred')
    op.drop_column('allowance_policies', 'is_additional_holiday_hundred')
    op.drop_table('part_timer_working_times')
    op.drop_table('part_timer_hourly_wages')
    op.drop_table('part_timer_additional_infos')
    op.drop_table('part_timer_work_contracts')
    op.drop_table('personnel_record_categories')
    # ### end Alembic commands ###
