"""v18

Revision ID: 91e9f0404a52
Revises: c6cf56d23a96
Create Date: 2024-11-04 20:57:28.145720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91e9f0404a52'
down_revision: Union[str, None] = 'c6cf56d23a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educations', 'school_type',
               existing_type=mysql.ENUM('ELEMENTARY', 'MIDDLE', 'HIGH', 'UNIVERSITY', 'GRADUATE'),
               type_=sa.Enum('초등학교', '중학교', '고등학교', '대학교', '대학원', name='school_type'),
               existing_nullable=True)
    op.alter_column('educations', 'graduation_type',
               existing_type=mysql.ENUM('GRADUATED', 'EXPECTED', 'IN_PROGRESS', 'LEAVE', 'DROPOUT'),
               type_=sa.Enum('졸업', '졸업예정', '재학중', '휴학', '중퇴', name='graduation_type'),
               existing_nullable=True)
    op.alter_column('users', 'part_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'part_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('educations', 'graduation_type',
               existing_type=sa.Enum('졸업', '졸업예정', '재학중', '휴학', '중퇴', name='graduation_type'),
               type_=mysql.ENUM('GRADUATED', 'EXPECTED', 'IN_PROGRESS', 'LEAVE', 'DROPOUT'),
               existing_nullable=True)
    op.alter_column('educations', 'school_type',
               existing_type=sa.Enum('초등학교', '중학교', '고등학교', '대학교', '대학원', name='school_type'),
               type_=mysql.ENUM('ELEMENTARY', 'MIDDLE', 'HIGH', 'UNIVERSITY', 'GRADUATE'),
               existing_nullable=True)
    # ### end Alembic commands ###
