"""update_close_day

Revision ID: 930046fbc4de
Revises: 091da39ca9b6
Create Date: 2024-10-17 10:30:41.354336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '930046fbc4de'
down_revision: Union[str, None] = '091da39ca9b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closed_days', sa.Column('part_id', sa.Integer(), nullable=True))
    op.add_column('closed_days', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('closed_days', 'branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'closed_days', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'closed_days', 'parts', ['part_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'closed_days', type_='foreignkey')
    op.drop_constraint(None, 'closed_days', type_='foreignkey')
    op.alter_column('closed_days', 'branch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('closed_days', 'user_id')
    op.drop_column('closed_days', 'part_id')
    # ### end Alembic commands ###
