"""v11

Revision ID: 97278b88c354
Revises: 13212fad6c7f
Create Date: 2024-11-02 15:58:43.915782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97278b88c354'
down_revision: Union[str, None] = '13212fad6c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('annual_salary', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('base_hour_per_week', sa.Integer(), nullable=False),
    sa.Column('base_hour_per_day', sa.Integer(), nullable=False),
    sa.Column('fixed_overtime_allowance', sa.Integer(), nullable=False),
    sa.Column('fixed_overtime_hours', sa.Integer(), nullable=False),
    sa.Column('annual_leave_allowance', sa.Integer(), nullable=False),
    sa.Column('annual_leave_hour_per_day', sa.Integer(), nullable=False),
    sa.Column('annual_leave_count', sa.Integer(), nullable=False),
    sa.Column('holiday_allowance', sa.Integer(), nullable=True),
    sa.Column('holiday_allowance_hours', sa.Integer(), nullable=False),
    sa.Column('duty_allowance', sa.Integer(), nullable=True),
    sa.Column('night_allowance', sa.Integer(), nullable=True),
    sa.Column('meal_allowance', sa.Integer(), nullable=True),
    sa.Column('vehicle_maintenance_allowance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_contract_id'), 'salary_contract', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_contract_id'), table_name='salary_contract')
    op.drop_table('salary_contract')
    # ### end Alembic commands ###
