"""파트타이머, 유저총연차, etc...

Revision ID: b5d61d151dd7
Revises: ed135c270209
Create Date: 2024-10-25 21:58:58.437507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b5d61d151dd7'
down_revision: Union[str, None] = 'ed135c270209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_leaves_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('leave_category_id', sa.Integer(), nullable=False),
    sa.Column('increased_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('decreased_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('total_leave_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['leave_category_id'], ['leave_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_leaves_days_user_id', 'user_leaves_days', ['user_id'], unique=False)
    op.drop_column('salary_templates', 'created_at')
    op.drop_column('salary_templates', 'updated_at')
    op.drop_column('salary_templates', 'deleted_yn')
    op.add_column('users', sa.Column('total_leave_days', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('is_part_timer', sa.Boolean(), nullable=False))
    op.alter_column('users', 'remaining_annual_leave',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'remaining_annual_leave',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('users', 'is_part_timer')
    op.drop_column('users', 'total_leave_days')
    op.add_column('salary_templates', sa.Column('deleted_yn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True))
    op.add_column('salary_templates', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('salary_templates', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_index('idx_user_leaves_days_user_id', table_name='user_leaves_days')
    op.drop_table('user_leaves_days')
    # ### end Alembic commands ###
