"""User, docs, contract 역참조 추가

Revision ID: be0ab647ec87
Revises: b5d61d151dd7
Create Date: 2024-10-25 22:00:07.524223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0ab647ec87'
down_revision: Union[str, None] = 'b5d61d151dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
