"""v17

Revision ID: c6cf56d23a96
Revises: 1bb64a706470
Create Date: 2024-11-04 16:49:06.152777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c6cf56d23a96'
down_revision: Union[str, None] = '1bb64a706470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educations', 'school_type',
               existing_type=mysql.ENUM('ELEMENTARY', 'MIDDLE', 'HIGH', 'UNIVERSITY', 'GRADUATE'),
               nullable=True)
    op.alter_column('educations', 'school_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('educations', 'graduation_type',
               existing_type=mysql.ENUM('GRADUATED', 'EXPECTED', 'IN_PROGRESS', 'LEAVE', 'DROPOUT'),
               nullable=True)
    op.alter_column('educations', 'admission_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educations', 'admission_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('educations', 'graduation_type',
               existing_type=mysql.ENUM('GRADUATED', 'EXPECTED', 'IN_PROGRESS', 'LEAVE', 'DROPOUT'),
               nullable=False)
    op.alter_column('educations', 'school_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('educations', 'school_type',
               existing_type=mysql.ENUM('ELEMENTARY', 'MIDDLE', 'HIGH', 'UNIVERSITY', 'GRADUATE'),
               nullable=False)
    # ### end Alembic commands ###
