"""message

Revision ID: c7e0eeb430fd
Revises: b5f80343a72e
Create Date: 2024-10-12 15:02:27.302273

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7e0eeb430fd"
down_revision: Union[str, None] = "b5f80343a72e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_yn", sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_yn", sa.String(length=1), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.Enum("MSO 최고권한", "최고관리자", "관리자", "사원", name="user_role"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_yn", sa.String(length=1), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.drop_table("overtimes")
    op.drop_table("annual_leaves")
    op.drop_table("personnel_records")
    op.drop_table("commutes")
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    op.add_column("users", sa.Column("address", sa.String(length=500), nullable=True))
    op.add_column("users", sa.Column("education", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column("users", sa.Column("hire_date", sa.Date(), nullable=True))
    op.add_column("users", sa.Column("resignation_date", sa.Date(), nullable=True))
    op.add_column(
        "users",
        sa.Column("gender", sa.Enum("남자", "여자", name="user_gender"), nullable=True),
    )
    op.add_column("users", sa.Column("part_id", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("branch_id", sa.Integer(), nullable=False))
    op.add_column(
        "users", sa.Column("last_company", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("last_position", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("last_career_start_date", sa.Date(), nullable=True)
    )
    op.add_column("users", sa.Column("last_career_end_date", sa.Date(), nullable=True))
    op.alter_column(
        "users", "name", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users", "email", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users", "password", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.create_unique_constraint(None, "users", ["email"])
    op.create_foreign_key(None, "users", "branches", ["branch_id"], ["id"])
    op.create_foreign_key(None, "users", "parts", ["part_id"], ["id"])
    op.drop_column("users", "role")
    op.drop_column("users", "part")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "part",
            mysql.ENUM(
                "외래팀",
                "관리",
                "의사",
                "총괄 상담실장",
                "간호조무사",
                "코디네이터",
                "피부관리자",
                "상담실장",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "role",
            mysql.ENUM("MSO 최고권한", "최고관리자", "관리자", "사원"),
            nullable=True,
        ),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "password", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "email", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "name", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.drop_column("users", "last_career_end_date")
    op.drop_column("users", "last_career_start_date")
    op.drop_column("users", "last_position")
    op.drop_column("users", "last_company")
    op.drop_column("users", "branch_id")
    op.drop_column("users", "part_id")
    op.drop_column("users", "gender")
    op.drop_column("users", "resignation_date")
    op.drop_column("users", "hire_date")
    op.drop_column("users", "birth_date")
    op.drop_column("users", "education")
    op.drop_column("users", "address")
    op.drop_column("users", "phone_number")
    op.create_table(
        "commutes",
        sa.Column("commute_id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("start_time", mysql.DATETIME(), nullable=True),
        sa.Column("end_time", mysql.DATETIME(), nullable=True),
        sa.Column("work_time", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.Column("deleted_yn", mysql.VARCHAR(length=1), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="commutes_ibfk_1"),
        sa.PrimaryKeyConstraint("commute_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "personnel_records",
        sa.Column(
            "personnel_record_id", mysql.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("manager_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("content", mysql.TEXT(), nullable=True),
        sa.Column(
            "category",
            mysql.ENUM("평가", "경고", "감사", "감봉", "해고"),
            nullable=True,
        ),
        sa.Column("created_at", mysql.DATETIME(), nullable=True),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.Column("deleted_yn", mysql.VARCHAR(length=1), nullable=True),
        sa.ForeignKeyConstraint(
            ["manager_id"], ["users.id"], name="personnel_records_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="personnel_records_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("personnel_record_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "annual_leaves",
        sa.Column(
            "annual_leave_id", mysql.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column("manager_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("proposer_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("application_date", mysql.DATETIME(), nullable=True),
        sa.Column(
            "type",
            mysql.ENUM(
                "annual_leave",
                "sick_leave",
                "bereavement_leave",
                "parental_leave",
                "leave_of_absence",
                "official_leave",
            ),
            nullable=True,
        ),
        sa.Column("date_count", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "application_status",
            mysql.ENUM("pending", "approved", "rejected"),
            nullable=True,
        ),
        sa.Column("proposer_note", mysql.TEXT(), nullable=True),
        sa.Column("manager_note", mysql.TEXT(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(), nullable=True),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.Column("deleted_yn", mysql.VARCHAR(length=1), nullable=True),
        sa.ForeignKeyConstraint(
            ["manager_id"], ["users.id"], name="annual_leaves_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["proposer_id"], ["users.id"], name="annual_leaves_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("annual_leave_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "overtimes",
        sa.Column("overtime_id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("manager_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("proposer_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("application_date", mysql.DATETIME(), nullable=True),
        sa.Column("ot_30", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ot_60", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ot_90", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ot_120", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("application_note", mysql.TEXT(), nullable=True),
        sa.Column("proposer_note", mysql.TEXT(), nullable=True),
        sa.Column("processed_date", mysql.DATETIME(), nullable=True),
        sa.Column(
            "application_status",
            mysql.ENUM("pending", "approved", "rejected"),
            nullable=True,
        ),
        sa.Column("created_at", mysql.DATETIME(), nullable=True),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.Column("deleted_yn", mysql.VARCHAR(length=1), nullable=True),
        sa.ForeignKeyConstraint(["manager_id"], ["users.id"], name="overtimes_ibfk_1"),
        sa.ForeignKeyConstraint(["proposer_id"], ["users.id"], name="overtimes_ibfk_2"),
        sa.PrimaryKeyConstraint("overtime_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("roles")
    op.drop_table("parts")
    op.drop_table("branches")
    # ### end Alembic commands ###
