"""v14

Revision ID: cfc0a931ae9c
Revises: baa4ae945ce6
Create Date: 2024-11-03 21:27:08.932980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfc0a931ae9c'
down_revision: Union[str, None] = 'baa4ae945ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel_record_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnel_record_category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('worker_comment', sa.String(length=255), nullable=False),
    sa.Column('admin_comment', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_yn', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['personnel_record_category_id'], ['personnel_record_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('personnel_record_categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('personnel_record_categories', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personnel_record_categories', sa.Column('description', mysql.VARCHAR(length=500), nullable=True))
    op.alter_column('personnel_record_categories', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_table('personnel_record_histories')
    # ### end Alembic commands ###
