"""v21

Revision ID: d3bdc1a85bc2
Revises: 2b5df9c1f68f
Create Date: 2024-11-05 18:30:03.692828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3bdc1a85bc2'
down_revision: Union[str, None] = '2b5df9c1f68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('careers', 'job_title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('careers', 'position',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('time_offs', sa.Column('is_paid', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('last_logout', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_logout')
    op.drop_column('time_offs', 'is_paid')
    op.alter_column('careers', 'position',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('careers', 'job_title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
