"""유저 모델 수정

Revision ID: ed135c270209
Revises: 9dcacee2bd41
Create Date: 2024-10-25 18:01:34.573284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text



# revision identifiers, used by Alembic.
revision: str = 'ed135c270209'
down_revision: Union[str, None] = '9dcacee2bd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('is_fixed_rest_day', sa.Boolean(), nullable=False),
    sa.Column('weekly_work_hours', sa.Integer(), nullable=False),
    sa.Column('weekly_work_start_time', sa.Time(), nullable=False),
    sa.Column('weekly_is_rest', sa.Boolean(), nullable=False),
    sa.Column('saturday_work_hours', sa.Integer(), nullable=True),
    sa.Column('saturday_work_start_time', sa.Time(), nullable=True),
    sa.Column('saturday_is_rest', sa.Boolean(), nullable=False),
    sa.Column('sunday_work_hours', sa.Integer(), nullable=True),
    sa.Column('sunday_work_start_time', sa.Time(), nullable=True),
    sa.Column('sunday_is_rest', sa.Boolean(), nullable=False),
    sa.Column('is_part_timer', sa.Boolean(), nullable=False),
    sa.Column('break_start_time', sa.Time(), nullable=True),
    sa.Column('break_end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_rest_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_contract_id', sa.Integer(), nullable=False),
    sa.Column('rest_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=False),
    sa.Column('every_over_week', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_contract_id'], ['work_contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('remaining_annual_leave', sa.Integer(), nullable=False, server_default=text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remaining_annual_leave')
    op.drop_table('fixed_rest_day')
    op.drop_table('work_contract')
    # ### end Alembic commands ###
