"""local_rds_v3

Revision ID: f1241103d37d
Revises: 2d6aa8b25a6e
Create Date: 2024-10-28 18:43:43.046175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1241103d37d'
down_revision: Union[str, None] = '2d6aa8b25a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def add_column_safe(table_name: str, column: sa.Column) -> None:
   try:
       op.add_column(table_name, column)
   except Exception as e:
       print(f"{table_name}의 {column.name} 컬럼 추가 스킵: {e}")

def drop_column_safe(table_name: str, column_name: str) -> None:
   try:
       op.drop_column(table_name, column_name)
   except Exception as e:
       print(f"{table_name}의 {column_name} 컬럼 삭제 스킵: {e}")

def upgrade() -> None:
   # ### commands auto generated by Alembic - please adjust! ###
   add_column_safe('users', 
       sa.Column('employment_status', sa.Enum('정규직', '계약직', name='employment_status'), nullable=False))
   drop_column_safe('users', 'is_part_timer')
   
   add_column_safe('work_contract', 
       sa.Column('weekly_work_end_time', sa.Time(), nullable=False))
   add_column_safe('work_contract', 
       sa.Column('saturday_work_end_time', sa.Time(), nullable=True))
   add_column_safe('work_contract', 
       sa.Column('sunday_work_end_time', sa.Time(), nullable=True))
       
   drop_column_safe('work_contract', 'weekly_work_hours')
   drop_column_safe('work_contract', 'sunday_work_hours')
   drop_column_safe('work_contract', 'saturday_work_hours')
   drop_column_safe('work_contract', 'is_part_timer')
   # ### end Alembic commands ###


def downgrade() -> None:
   # ### commands auto generated by Alembic - please adjust! ###
   add_column_safe('work_contract', 
       sa.Column('is_part_timer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
   add_column_safe('work_contract', 
       sa.Column('saturday_work_hours', mysql.INTEGER(), autoincrement=False, nullable=True))
   add_column_safe('work_contract', 
       sa.Column('sunday_work_hours', mysql.INTEGER(), autoincrement=False, nullable=True))
   add_column_safe('work_contract', 
       sa.Column('weekly_work_hours', mysql.INTEGER(), autoincrement=False, nullable=False))
       
   drop_column_safe('work_contract', 'sunday_work_end_time')
   drop_column_safe('work_contract', 'saturday_work_end_time')
   drop_column_safe('work_contract', 'weekly_work_end_time')
   
   add_column_safe('users', 
       sa.Column('is_part_timer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
   drop_column_safe('users', 'employment_status')
   # ### end Alembic commands ###