
services:
  mysql:
    image: mysql:8.0
    container_name: local-db
    ports:
      - 3308:3306
    environment:
      TZ: Asia/Seoul
    env_file: ../.env.dev
    command:
      - --character-set-server=UTF8MB4
      - --collation-server=UTF8MB4_UNICODE_CI