name: Deploy to Server

on:
  push:
    branches:
      - deploy_only

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: deploy_only

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            cd ~/checks-be/workswave-backend 
            git fetch origin
            git checkout deploy_only
            git reset --hard origin/deploy_only
            docker stop $(docker ps -aq) || true
            docker rm $(docker ps -aq) || true
            docker rmi $(docker images -q) || true
            docker rmi -f $(docker images -q) || true
            yes | docker system prune -a || true
            yes | docker volume prune || true
            yes | docker builder prune || true
            docker volume rm $(docker volume ls -q) || true
            docker-compose -f docker-compose.yml up --build -d